# Generated by Django 3.2.9 on 2021-12-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211205_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='moremoo', max_length=255, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
