# Generated by Django 3.2.9 on 2021-12-06 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roots', '0005_contactinfo'),
        ('users', '0004_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roots.contactinfo'),
        ),
    ]
