# Generated by Django 3.2.9 on 2021-12-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roots', '0004_alter_classroom_children'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('postal_code', models.CharField(max_length=255, verbose_name='Postal Code')),
                ('province', models.CharField(max_length=255, verbose_name='Province')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('phone1', models.CharField(max_length=255, verbose_name='Phone Number 1')),
                ('phone2', models.CharField(max_length=255, verbose_name='Phone Number 2')),
            ],
        ),
    ]
