# Generated by Django 3.2.9 on 2021-12-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roots', '0005_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='province',
            field=models.CharField(choices=[('AB', 'AB'), ('BC', 'BC'), ('MB', 'MB'), ('NB', 'NB'), ('NL', 'NL'), ('NS', 'NS'), ('NT', 'NT'), ('NU', 'NU'), ('ON', 'ON'), ('PE', 'PE'), ('QC', 'QC'), ('SK', 'SK'), ('YT', 'YT')], default='BC', max_length=2),
        ),
    ]
