# Generated by Django 3.2.9 on 2021-12-06 19:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('roots', '0006_alter_contactinfo_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='phone1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
