# Generated by Django 3.2.9 on 2021-12-06 20:21

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roots', '0008_alter_classroom_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='children',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('food', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('classrooms', models.ManyToManyField(blank=True, to='roots.Classroom')),
            ],
        ),
    ]
