# Generated by Django 3.2.9 on 2021-12-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roots', '0009_auto_20211206_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='food',
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('menus', models.ManyToManyField(blank=True, to='roots.Menu')),
            ],
        ),
    ]
