# Generated by Django 3.2.9 on 2021-12-06 20:52

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roots', '0010_auto_20211206_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('children', models.ManyToManyField(blank=True, limit_choices_to={'role': 'CHILD'}, to=settings.AUTH_USER_MODEL)),
                ('classrooms', models.ManyToManyField(blank=True, to='roots.Classroom')),
                ('food', models.ManyToManyField(blank=True, to='roots.Food')),
                ('menu', models.ManyToManyField(blank=True, to='roots.Menu')),
            ],
        ),
    ]
