# Generated by Django 3.2.9 on 2021-12-07 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roots', '0011_auto_20211206_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('role', models.CharField(choices=[('CHILD', 'Child'), ('PARENT', 'Parent'), ('STAFF', 'Staff')], default='CHILD', max_length=6)),
                ('contact_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roots.contactinfo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roots.person')),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='children',
            field=models.ManyToManyField(blank=True, to='roots.Child'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='children',
            field=models.ManyToManyField(blank=True, to='roots.Child'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='children',
            field=models.ManyToManyField(blank=True, to='roots.Child'),
        ),
    ]
