# Generated by Django 3.2.9 on 2021-12-08 16:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
import roots.models


class Migration(migrations.Migration):

    dependencies = [
        ('roots', '0012_auto_20211207_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('end_time', models.TimeField(default=roots.models.get_time, verbose_name='End Time')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('start_time', models.TimeField(default=roots.models.get_time, verbose_name='Start Time')),
                ('children', models.ManyToManyField(blank=True, null=True, to='roots.Child')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roots.parent')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roots.child')),
            ],
        ),
        migrations.CreateModel(
            name='Toileting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('end_time', models.TimeField(default=roots.models.get_time, verbose_name='End Time')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('start_time', models.TimeField(default=roots.models.get_time, verbose_name='Start Time')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roots.child')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='end_time',
            field=models.TimeField(default=roots.models.get_time, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='meal',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='meal',
            name='start_time',
            field=models.TimeField(default=roots.models.get_time, verbose_name='Start Time'),
        ),
        migrations.AddField(
            model_name='menu',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, to='roots.Child'),
        ),
        migrations.AlterField(
            model_name='food',
            name='menus',
            field=models.ManyToManyField(blank=True, null=True, to='roots.Menu'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, to='roots.Child'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='classrooms',
            field=models.ManyToManyField(blank=True, null=True, to='roots.Classroom'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='food',
            field=models.ManyToManyField(blank=True, null=True, to='roots.Food'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='menu',
            field=models.ManyToManyField(blank=True, null=True, to='roots.Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='classrooms',
            field=models.ManyToManyField(blank=True, null=True, to='roots.Classroom'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.AddField(
            model_name='registration',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roots.classroom'),
        ),
        migrations.AddField(
            model_name='registration',
            name='parents',
            field=models.ManyToManyField(blank=True, null=True, to='roots.Parent'),
        ),
        migrations.AddField(
            model_name='child',
            name='parents',
            field=models.ManyToManyField(blank=True, null=True, to='roots.Parent'),
        ),
    ]
