# Generated by Django 3.2.9 on 2021-12-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roots', '0013_auto_20211208_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='children',
            field=models.ManyToManyField(blank=True, to='roots.Child'),
        ),
        migrations.AlterField(
            model_name='food',
            name='menus',
            field=models.ManyToManyField(blank=True, to='roots.Menu'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='children',
            field=models.ManyToManyField(blank=True, to='roots.Child'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='classrooms',
            field=models.ManyToManyField(blank=True, to='roots.Classroom'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='food',
            field=models.ManyToManyField(blank=True, to='roots.Food'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='menu',
            field=models.ManyToManyField(blank=True, to='roots.Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='classrooms',
            field=models.ManyToManyField(blank=True, to='roots.Classroom'),
        ),
        migrations.AlterField(
            model_name='nap',
            name='children',
            field=models.ManyToManyField(blank=True, to='roots.Child'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='parents',
            field=models.ManyToManyField(blank=True, to='roots.Parent'),
        ),
    ]
