# Generated by Django 3.2.9 on 2021-12-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roots', '0014_auto_20211208_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parents',
            field=models.ManyToManyField(blank=True, to='roots.Parent'),
        ),
    ]
