# Generated by Django 3.2.9 on 2021-12-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roots', '0015_alter_child_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='country',
            field=models.CharField(default='Canada', max_length=255, verbose_name='Country'),
        ),
    ]
