# Generated by Django 3.2.9 on 2021-12-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roots', '0017_alter_person_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Family Name')),
                ('children', models.ManyToManyField(blank=True, related_name='children', to='roots.Person')),
                ('parents', models.ManyToManyField(blank=True, related_name='parents', to='roots.Person')),
            ],
        ),
    ]
