# Generated by Django 3.2.9 on 2021-12-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roots', '0018_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='menus',
        ),
        migrations.AddField(
            model_name='menu',
            name='food',
            field=models.ManyToManyField(blank=True, to='roots.Food'),
        ),
    ]
