# Generated by Django 3.2.9 on 2021-12-13 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roots', '0020_toileting_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Start Date'),
        ),
    ]
