# Generated by Django 3.2.9 on 2021-12-13 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roots', '0021_alter_registration_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='end_date',
        ),
    ]
